data:
    dataset: "office-31"
    seed: 1
    num_classes: 31
    num_workers: 4
    dataroot: './data_list/office'
    source_domain: 'webcam'
    target_domain: 'amazon'

model:
    data_dim: 256
    hidden_dim: 512
    feature_dim: 256
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True

diffusion:
    beta_schedule: linear  # cosine_anneal, cosine
    beta_start: 0.0001 #
    beta_end: 0.02 #
    timesteps: 1000 #
    # trained_aux_cls_ckpt_path: ""
    # trained_aux_cls_ckpt_name: ""
    aux_cls:
        h_dim: 512 #
        z_dim: 256 #
        pre_train: True #
        joint_train: False #
        n_pretrain_epochs: 5 #
        source_pretrain_epochs: 0 # only used for SFADA
        logging_interval: 1 #
    
training:
    batch_size: 32
    weight_kl: 0.1 ##
    weight_kd: 0.1 ##
    weight_transfer: 1.0 ##
    n_epochs: 10 ###
    open_backbone: False
    warmup_epochs_adaptation: 20
    warmup_epochs_diffusion: 50
    snapshot_freq: 1000000000
    validation_freq: 50
    active: 'ttest'

testing:
    batch_size: 32
    sampling_size: 1000
    n_samples: 100
    n_bins: 10
    PICP_range: [2.5, 97.5]

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: False
    eps: 0.00000001
    grad_clip: 1.0
    lr_schedule: True
    min_lr: 0.0

aux_optim:
    weight_decay: 0.001
    optimizer: "SGD"
    lr: 0.01
    beta1: 0.9
    amsgrad: True
    eps: 0.00000001
    grad_clip: 1.0